### PR TITLE
Migration to RISC-V specifications template in asciidoc

### PR DESCRIPTION
**Pull request by apazos**
TODOs:
- Fix rendering of Chinese characters in the generated PDF file. Characters referenced in
https://github.com/riscv-non-isa/riscv-toolchain-conventions#list-of-vendor-prefixes

- Fix reference to RISC-V Assembly Programmer's Manual after migration to RVI template is merged.

### CODE REVIEW

**Comment by apazos** [comment]
Pushed changes to make title page and toc appear, reorganizing prelude and preamble files

**Comment by apazos** [comment]
Moved list of tables after document status

**Comment by cmuellner** [comment]
I could reproduce the issue with the generation of Chinese characters. @wmat, can you comment on that? What we want to achieve can be seen in the [markdown rendering](https://github.com/riscv-non-isa/riscv-toolchain-conventions/blob/main/README.mkd#list-of-vendor-prefixes) (just search for "Nuclei").

The rest looks good and ready to land.

**Comment by wmat** [comment]
Chinese characters should render fine in the PDF.  In this particular case, if they're only in the README, you can leave it as mkd as it's not included as part of the PDF.

**Comment by wmat** [comment]
The build isn't picking up the theme from docs-resources.  Here's what I get when I build locally:

Screenshot from 2024-08-28 08-57-56

I pushed the fix.

**Comment by cmuellner** [comment]
@wmat, thank you very much! Works now here as well!

**Review by cmuellner — APPROVED** [review]
LGTM

**Comment by apazos** [comment]
Thanks a lot, @wmat for fixing the Chinese characters issue.

**Pull request merged**
