### PR TITLE
Add large code model

### PR DESCRIPTION
**Pull request by tclin914**

### CODE REVIEW

**Comment by cmuellner** [comment]
This looks good in general.

When double-checking with the implementations, I saw that LLVM does not create `__riscv_cmodel_large`. We should probably close this gap before merging this PR.

**Review by cmuellner — APPROVED** [review]
LGTM

**Comment by cmuellner** [comment]
@asb and @kito-cheng: any objections to merging this?

It looks like this is needed for https://github.com/llvm/llvm-project/pull/107817

**Review by kito-cheng — APPROVED** [review]
LGTM :)

**Comment by asb** [comment]
In parallel I'd added the define to riscv-c-api-doc in https://github.com/riscv-non-isa/riscv-c-api-doc/pull/86

This listing of defines comes from when this repo was little more than my personal notes on what GCC does and Clang should probably do to follow suit. Now that we have the preprocessor defines listed authoritatively in riscv-c-api-doc I think it makes sense to remove them from this document, which https://github.com/riscv-non-isa/riscv-toolchain-conventions/pull/61 does.

**Pull request merged**
