### PR TITLE
Update to latest CI/CD scripts from docs-template repo

### PR DESCRIPTION
**Pull request by cmuellner**
This adds the file `pre-commit.yml` which is in the docs-template repo, but not in this repo.

### CODE REVIEW

**Comment by cmuellner** [comment]
@apazos, @kito-cheng, or @wmat, please review.

**Comment by wmat** [comment]
LGTM

**Comment by cmuellner** [comment]
@wmat, do you have permission to "approve" the PR? I want to avoid bypassing the branch protections, and I cannot approve my own PR.

**Review by wmat — APPROVED** [review]

**Comment by wmat** [comment]
Approved.  I can merge it as well if you like?

**Pull request merged**
